import { serve } from 'https://deno.land/std@0.177.0/http/server.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req: Request) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const authHeader = req.headers.get('Authorization')!
    const supabaseClient = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_ANON_KEY') ?? '',
      { global: { headers: { Authorization: authHeader } } }
    )

    const { data: { user } } = await supabaseClient.auth.getUser()
    if (!user) {
      return new Response(JSON.stringify({ error: 'Unauthorized' }), { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } })
    }

    const { passport_id, include_history } = await req.json()

    // Fetch user profile
    const { data: userProfile } = await supabaseClient
      .from('users')
      .select('*')
      .eq('id', user.id)
      .single()

    // Fetch health passport
    const { data: passport } = await supabaseClient
      .from('health_passports')
      .select('*')
      .eq('id', passport_id || '')
      .eq('user_id', user.id)
      .single()

    // Fetch symptom history if requested
    let symptomHistory: any[] = []
    if (include_history) {
      const { data: logs } = await supabaseClient
        .from('symptom_logs')
        .select('*')
        .eq('user_id', user.id)
        .order('logged_at', { ascending: false })
        .limit(30)
      symptomHistory = logs || []
    }

    // Build PDF data as structured JSON (client will render the actual PDF)
    const pdfData = {
      header: {
        app_name: 'VitalSeker',
        tagline: 'AI Health Companion',
        producer: 'Keter Marketing',
        generated_at: new Date().toISOString(),
      },
      patient: {
        name: userProfile?.full_name || 'Unknown',
        email: userProfile?.email || user.email,
        date_of_birth: userProfile?.date_of_birth,
        blood_type: passport?.blood_type || userProfile?.blood_type,
      },
      health_passport: passport ? {
        vital_score: passport.vital_score,
        blood_type: passport.blood_type,
        allergies: passport.allergies,
        medications: passport.medications,
        chronic_conditions: passport.chronic_conditions,
        emergency_contacts: passport.emergency_contacts,
        insurance_provider: passport.insurance_provider,
        insurance_policy_number: passport.insurance_policy_number,
        last_assessment: passport.last_assessment_date,
      } : null,
      symptom_history: include_history ? symptomHistory.map(log => ({
        date: log.logged_at,
        symptoms: log.symptoms,
        severity: log.severity,
        triage_result: log.triage_result,
        recommendation: log.ai_recommendation,
      })) : [],
      footer: {
        disclaimer: 'This document is generated by VitalSeker AI Health Companion and does not constitute a medical diagnosis. Always consult a qualified healthcare professional.',
        producer: 'Powered by Keter Marketing',
      },
    }

    return new Response(JSON.stringify(pdfData), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })
  } catch (error) {
    console.error('Export PDF error:', error)
    return new Response(JSON.stringify({ error: 'Internal server error' }), { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } })
  }
})
