import 'package:flutter/material.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:audioplayers/audioplayers.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:timezone/data/latest.dart' as tz;
import 'package:timezone/timezone.dart' as tz;

/// Notification service for scheduling and displaying local notifications
/// with custom sounds. Per Cahier des Charges Section 3: "Notifications —
/// OneSignal — Push notifications, rappels, alertes santé".
///
/// This service handles:
/// - Daily triage reminders (e.g., 9:00 AM)
/// - Medication reminders
/// - Weekly insights notifications
/// - Custom ringtone selection per notification type
/// - Sound preview playback (tap to play, tap to stop)
class NotificationService {
  static final NotificationService _instance = NotificationService._internal();
  factory NotificationService() => _instance;
  NotificationService._internal();

  final FlutterLocalNotificationsPlugin _plugin = FlutterLocalNotificationsPlugin();
  final AudioPlayer _audioPlayer = AudioPlayer();
  bool _initialized = false;

  /// Notification channel IDs
  static const String _channelReminders = 'vitalseker_reminders';
  static const String _channelInsights = 'vitalseker_insights';
  static const String _channelMedications = 'vitalseker_medications';
  static const String _channelAppointments = 'vitalseker_appointments';
  static const String _channelVitals = 'vitalseker_vitals';

  /// Available notification sounds (raw resources in android/app/src/main/res/raw/)
  /// Each sound is a short WAV file generated by scripts/generate_notification_sounds.py
  /// The display name maps to the raw resource filename (without extension).
  static const Map<String, String> availableSounds = {
    'Default': 'notification',
    'Chime': 'chime',
    'Alert': 'alert',
    'Bell': 'bell',
    'Soft': 'soft',
    'Pulse': 'pulse',
    'Sparkle': 'sparkle',
    'Gentle': 'gentle',
    'Marimba': 'marimba',
    'Cosmic': 'cosmic',
  };

  /// Reverse map: raw resource name → display name
  static String soundDisplayName(String rawName) {
    return availableSounds.entries
        .firstWhere(
          (e) => e.value == rawName,
          orElse: () => const MapEntry('Default', 'notification'),
        )
        .key;
  }

  bool get isInitialized => _initialized;

  Future<void> initialize() async {
    if (_initialized) return;

    // Initialize timezone data for scheduled notifications
    tz.initializeTimeZones();

    const androidSettings = AndroidInitializationSettings('@mipmap/ic_launcher');
    const iosSettings = DarwinInitializationSettings(
      requestAlertPermission: true,
      requestBadgePermission: true,
      requestSoundPermission: true,
    );
    const settings = InitializationSettings(android: androidSettings, iOS: iosSettings);

    await _plugin.initialize(
      settings,
      onDidReceiveNotificationResponse: (response) {
        debugPrint('[Notifications] Tapped: ${response.payload}');
      },
    );

    // Create notification channels with custom sounds
    await _createChannels();

    _initialized = true;
    debugPrint('[Notifications] Initialized');
  }

  Future<void> _createChannels() async {
    // Reminders channel (daily triage reminders)
    const remindersChannel = AndroidNotificationChannel(
      _channelReminders,
      'Health Reminders',
      description: 'Daily health check + triage reminders',
      importance: Importance.high,
      sound: RawResourceAndroidNotificationSound('notification'),
    );

    // Insights channel (weekly insights + health tips)
    const insightsChannel = AndroidNotificationChannel(
      _channelInsights,
      'Weekly Insights & Tips',
      description: 'Weekly AI health insights and health tips',
      importance: Importance.defaultImportance,
      sound: RawResourceAndroidNotificationSound('notification'),
    );

    // Medications channel (medication reminders)
    const medicationsChannel = AndroidNotificationChannel(
      _channelMedications,
      'Medication Reminders',
      description: 'Medication schedule reminders',
      importance: Importance.high,
      sound: RawResourceAndroidNotificationSound('notification'),
    );

    // Appointments channel (appointment reminders)
    const appointmentsChannel = AndroidNotificationChannel(
      _channelAppointments,
      'Appointment Reminders',
      description: 'Doctor appointment reminders',
      importance: Importance.high,
      sound: RawResourceAndroidNotificationSound('notification'),
    );

    // Vitals channel (vitals logging reminders)
    const vitalsChannel = AndroidNotificationChannel(
      _channelVitals,
      'Vitals Logging Reminders',
      description: 'Reminders to log your vitals',
      importance: Importance.defaultImportance,
      sound: RawResourceAndroidNotificationSound('notification'),
    );

    final androidPlugin = _plugin
        .resolvePlatformSpecificImplementation<AndroidFlutterLocalNotificationsPlugin>();
    await androidPlugin?.createNotificationChannel(remindersChannel);
    await androidPlugin?.createNotificationChannel(insightsChannel);
    await androidPlugin?.createNotificationChannel(medicationsChannel);
    await androidPlugin?.createNotificationChannel(appointmentsChannel);
    await androidPlugin?.createNotificationChannel(vitalsChannel);
  }

  /// Show an immediate notification.
  Future<void> showNotification({
    required String title,
    required String body,
    String channelId = _channelReminders,
    String? sound,
    int id = 0,
  }) async {
    if (!_initialized) await initialize();

    final androidDetails = AndroidNotificationDetails(
      channelId,
      channelId == _channelReminders ? 'Health Reminders' : 'Notifications',
      importance: Importance.high,
      priority: Priority.high,
      sound: sound != null
          ? RawResourceAndroidNotificationSound(sound)
          : const RawResourceAndroidNotificationSound('notification'),
      icon: '@mipmap/ic_launcher',
    );

    const iosDetails = DarwinNotificationDetails(
      presentAlert: true,
      presentBadge: true,
      presentSound: true,
    );

    final details = NotificationDetails(android: androidDetails, iOS: iosDetails);

    await _plugin.show(id, title, body, details);
  }

  /// Schedule a daily notification at a specific hour.
  ///
  /// FIX (audit M-17): delegate to _scheduleDaily instead of duplicating its
  /// logic. The previous implementation didn't use _getSavedSound (always
  /// hardcoded 'notification') and didn't use _channelName.
  Future<void> scheduleDailyReminder({
    required int hour,
    required int minute,
    required String title,
    required String body,
    String channelId = _channelReminders,
    int id = 0,
  }) async {
    await _scheduleDaily(
      id: id,
      channelId: channelId,
      hour: hour,
      minute: minute,
      title: title,
      body: body,
    );

    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool('notif_reminder_enabled', true);
    await prefs.setInt('notif_reminder_hour', hour);
    await prefs.setInt('notif_reminder_minute', minute);
  }

  /// Cancel a scheduled notification by ID.
  ///
  /// FIX (audit M-16): handle IDs 0-4 (previously only 0-2). IDs 3 (health
  /// tips) and 4 (weekly report) were not handled, so cancelling them didn't
  /// reset the SharedPreferences flag — the UI showed them as enabled even
  /// after cancellation.
  Future<void> cancelNotification(int id) async {
    await _plugin.cancel(id);
    final prefs = await SharedPreferences.getInstance();
    switch (id) {
      case 0: await prefs.setBool('notif_reminder_enabled', false); break;
      case 1: await prefs.setBool('notif_medications_enabled', false); break;
      case 2: await prefs.setBool('notif_vitals_enabled', false); break;
      case 3: await prefs.setBool('notif_tips_enabled', false); break;
      case 4: await prefs.setBool('notif_insights_enabled', false); break;
      // Appointment reminders use IDs >= 100 (see scheduleAppointmentReminder).
      // They don't have a prefs flag — cancelling the plugin notification is
      // sufficient.
      default: break;
    }
  }

  /// Cancel all notifications.
  Future<void> cancelAll() async {
    await _plugin.cancelAll();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool('notif_reminder_enabled', false);
    await prefs.setBool('notif_medications_enabled', false);
    await prefs.setBool('notif_vitals_enabled', false);
    await prefs.setBool('notif_tips_enabled', false);
    await prefs.setBool('notif_insights_enabled', false);
  }

  /// Set a custom sound for a notification channel.
  Future<void> setCustomSound(String channelId, String soundName) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('notif_sound_$channelId', soundName);

    // Recreate the channel with the new sound
    final channel = AndroidNotificationChannel(
      channelId,
      _channelName(channelId),
      description: 'Custom sound: $soundName',
      importance: Importance.high,
      sound: RawResourceAndroidNotificationSound(soundName),
    );

    await _plugin
        .resolvePlatformSpecificImplementation<AndroidFlutterLocalNotificationsPlugin>()
        ?.createNotificationChannel(channel);
  }

  String _channelName(String id) {
    switch (id) {
      case _channelReminders:
        return 'Health Reminders';
      case _channelInsights:
        return 'Weekly Insights & Tips';
      case _channelMedications:
        return 'Medication Reminders';
      case _channelAppointments:
        return 'Appointment Reminders';
      case _channelVitals:
        return 'Vitals Logging Reminders';
      default:
        return 'Notifications';
    }
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // SOUND PREVIEW PLAYBACK
  // ═══════════════════════════════════════════════════════════════════════════

  /// Play a sound preview using the audioplayers package.
  ///
  /// Plays the sound from the Android raw resource (without the .wav
  /// extension). If a sound is already playing, it is stopped first —
  /// so tapping the same sound twice will play→stop→play.
  ///
  /// Returns true if the sound started playing, false if it was stopped
  /// (or if playback failed).
  Future<bool> previewSound(String soundName) async {
    try {
      // If already playing, stop and return false (toggle off)
      if (_audioPlayer.state == PlayerState.playing) {
        await _audioPlayer.stop();
        return false;
      }
      // Play from the raw resource. On Android, audioplayers loads
      // from 'assets/sounds/' or from a raw resource URL. We use the
      // asset path 'sounds/$soundName.wav' — the files are bundled as
      // Flutter assets (declared in pubspec.yaml) AND as Android raw
      // resources (for notification channel playback).
      await _audioPlayer.play(AssetSource('sounds/$soundName.wav'));
      return true;
    } catch (e) {
      debugPrint('[Notifications] Sound preview failed: $e');
      return false;
    }
  }

  /// Stop any currently-playing sound preview.
  Future<void> stopPreview() async {
    try {
      await _audioPlayer.stop();
    } catch (e) {
      debugPrint('[Notifications] Stop preview failed: $e');
    }
  }

  /// Whether a sound preview is currently playing.
  bool get isPreviewing => _audioPlayer.state == PlayerState.playing;

  /// Dispose the audio player — call from the screen's dispose() method.
  void disposeAudioPlayer() {
    _audioPlayer.dispose();
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // PER-REMINDER-TYPE SCHEDULING
  // ═══════════════════════════════════════════════════════════════════════════

  /// Schedule a triage reminder (daily health check).
  /// Notification ID: 0. Channel: vitalseker_reminders.
  Future<void> scheduleTriageReminder({
    required int hour,
    required int minute,
    String? sound,
  }) async {
    await _scheduleDaily(
      id: 0,
      channelId: _channelReminders,
      hour: hour,
      minute: minute,
      title: 'VitalSeker Health Check',
      body: 'Time for your daily health check. Tap to start a triage.',
      sound: sound,
    );
  }

  /// Schedule a medication reminder.
  /// Notification ID: 1. Channel: vitalseker_medications.
  Future<void> scheduleMedicationReminder({
    required int hour,
    required int minute,
    String? sound,
  }) async {
    await _scheduleDaily(
      id: 1,
      channelId: _channelMedications,
      hour: hour,
      minute: minute,
      title: 'Medication Reminder',
      body: 'It\u2019s time to take your medication. Tap for details.',
      sound: sound,
    );
  }

  /// Schedule a vitals logging reminder.
  /// Notification ID: 2. Channel: vitalseker_vitals.
  Future<void> scheduleVitalsReminder({
    required int hour,
    required int minute,
    String? sound,
  }) async {
    await _scheduleDaily(
      id: 2,
      channelId: _channelVitals,
      hour: hour,
      minute: minute,
      title: 'Log Your Vitals',
      body: 'Time to log your heart rate, blood pressure, or other vitals.',
      sound: sound,
    );
  }

  /// Schedule a health tips reminder (3x per week or daily).
  /// Notification ID: 3. Channel: vitalseker_insights.
  Future<void> scheduleHealthTipsReminder({
    required int hour,
    required int minute,
    String? sound,
  }) async {
    await _scheduleDaily(
      id: 3,
      channelId: _channelInsights,
      hour: hour,
      minute: minute,
      title: 'Health Tip of the Day',
      body: 'Discover a new health tip tailored to your profile. Tap to read.',
      sound: sound,
    );
  }

  /// Schedule a weekly report reminder.
  /// Notification ID: 4. Channel: vitalseker_insights.
  /// [weekday] is 1=Monday ... 7=Sunday (ISO 8601).
  Future<void> scheduleWeeklyReportReminder({
    required int weekday,
    required int hour,
    required int minute,
    String? sound,
  }) async {
    if (!_initialized) await initialize();

    final now = tz.TZDateTime.now(tz.local);
    var scheduled = tz.TZDateTime(tz.local, now.year, now.month, now.day, hour, minute);
    // FIX (audit M-18): validate weekday is in [1, 7] to prevent an
    // infinite loop. If weekday is 0, 8, or negative, the while condition
    // `scheduled.weekday != weekday` is always true and the loop never exits.
    if (weekday < 1 || weekday > 7) {
      debugPrint('[Notifications] Invalid weekday $weekday — must be 1-7. Defaulting to 1 (Monday).');
    }
    final targetWeekday = (weekday < 1 || weekday > 7) ? 1 : weekday;
    // Advance to the target weekday
    int safetyCounter = 0;
    while ((scheduled.weekday != targetWeekday || scheduled.isBefore(now)) && safetyCounter < 14) {
      scheduled = scheduled.add(const Duration(days: 1));
      safetyCounter++;
    }

    final soundName = sound ?? await _getSavedSound(_channelInsights);
    final androidDetails = AndroidNotificationDetails(
      _channelInsights,
      'Weekly Report',
      importance: Importance.defaultImportance,
      priority: Priority.defaultPriority,
      sound: RawResourceAndroidNotificationSound(soundName),
      icon: '@mipmap/ic_launcher',
    );
    const iosDetails = DarwinNotificationDetails(
      presentAlert: true,
      presentBadge: true,
      presentSound: true,
    );
    final details = NotificationDetails(android: androidDetails, iOS: iosDetails);

    await _plugin.zonedSchedule(
      4,
      'Your Weekly Health Report',
      'Your weekly health insights are ready. Tap to view your trends and AI recommendations.',
      scheduled,
      details,
      androidScheduleMode: AndroidScheduleMode.exactAllowWhileIdle,
      uiLocalNotificationDateInterpretation: UILocalNotificationDateInterpretation.absoluteTime,
      matchDateTimeComponents: DateTimeComponents.dayOfWeekAndTime,
    );
  }

  /// Schedule an appointment reminder (1 day before, or at a specific offset).
  /// Notification ID: 5+. Channel: vitalseker_appointments.
  Future<void> scheduleAppointmentReminder({
    required int notificationId,
    required DateTime appointmentDateTime,
    required Duration leadTime,
    String? sound,
  }) async {
    if (!_initialized) await initialize();

    final reminderTime = appointmentDateTime.subtract(leadTime);
    if (reminderTime.isBefore(DateTime.now())) return; // Already past

    final scheduled = tz.TZDateTime.from(reminderTime, tz.local);
    final soundName = sound ?? await _getSavedSound(_channelAppointments);
    final androidDetails = AndroidNotificationDetails(
      _channelAppointments,
      'Appointment Reminder',
      importance: Importance.high,
      priority: Priority.high,
      sound: RawResourceAndroidNotificationSound(soundName),
      icon: '@mipmap/ic_launcher',
    );
    const iosDetails = DarwinNotificationDetails(
      presentAlert: true,
      presentBadge: true,
      presentSound: true,
    );
    final details = NotificationDetails(android: androidDetails, iOS: iosDetails);

    await _plugin.zonedSchedule(
      notificationId,
      'Upcoming Appointment',
      'You have a doctor\u2019s appointment on ${appointmentDateTime.day}/${appointmentDateTime.month} at ${appointmentDateTime.hour}:${appointmentDateTime.minute.toString().padLeft(2, '0')}.',
      scheduled,
      details,
      androidScheduleMode: AndroidScheduleMode.exactAllowWhileIdle,
      uiLocalNotificationDateInterpretation: UILocalNotificationDateInterpretation.absoluteTime,
    );
  }

  /// Internal helper: schedule a daily repeating notification.
  Future<void> _scheduleDaily({
    required int id,
    required String channelId,
    required int hour,
    required int minute,
    required String title,
    required String body,
    String? sound,
  }) async {
    if (!_initialized) await initialize();

    final now = tz.TZDateTime.now(tz.local);
    var scheduled = tz.TZDateTime(tz.local, now.year, now.month, now.day, hour, minute);
    if (scheduled.isBefore(now)) {
      scheduled = scheduled.add(const Duration(days: 1));
    }

    final soundName = sound ?? await _getSavedSound(channelId);
    final androidDetails = AndroidNotificationDetails(
      channelId,
      _channelName(channelId),
      importance: channelId == _channelReminders || channelId == _channelMedications || channelId == _channelAppointments
          ? Importance.high
          : Importance.defaultImportance,
      priority: channelId == _channelReminders || channelId == _channelMedications || channelId == _channelAppointments
          ? Priority.high
          : Priority.defaultPriority,
      sound: RawResourceAndroidNotificationSound(soundName),
      icon: '@mipmap/ic_launcher',
    );
    const iosDetails = DarwinNotificationDetails(
      presentAlert: true,
      presentBadge: true,
      presentSound: true,
    );
    final details = NotificationDetails(android: androidDetails, iOS: iosDetails);

    await _plugin.zonedSchedule(
      id,
      title,
      body,
      scheduled,
      details,
      androidScheduleMode: AndroidScheduleMode.exactAllowWhileIdle,
      uiLocalNotificationDateInterpretation: UILocalNotificationDateInterpretation.absoluteTime,
      matchDateTimeComponents: DateTimeComponents.time,
    );
  }

  /// Get the saved custom sound for a channel (or 'notification' default).
  Future<String> _getSavedSound(String channelId) async {
    final prefs = await SharedPreferences.getInstance();
    return prefs.getString('notif_sound_$channelId') ?? 'notification';
  }
}
