class AppConfig {
  static const String appName = 'VitalSeker';
  static const String appTagline = 'Your AI Health Companion';
  static const String producer = 'Keter Marketing';
  static const String version = '1.0.0';
  static const double proPriceMonthly = 6.99;
  static const double enterprisePriceMonthly = 199.0;
  
  // Route paths
  static const String splash = '/';
  static const String onboarding = '/onboarding';
  static const String login = '/login';
  static const String register = '/register';
  static const String resetPassword = '/reset-password';
  static const String home = '/home';
  static const String dashboard = '/home/dashboard';
  static const String health = '/home/health';
  static const String triage = '/home/triage';
  static const String triageResult = '/home/triage/result';
  static const String passport = '/home/passport';
  static const String qrDisplay = '/home/passport/qr';
  static const String history = '/home/history';
  static const String insights = '/home/insights';
  static const String family = '/home/family';
  static const String exportScreen = '/home/export';
  static const String sos = '/home/sos';
  static const String profile = '/home/profile';
  static const String about = '/home/profile/about';
  static const String subscription = '/home/profile/subscription';
  static const String editProfile = '/home/profile/edit';
  static const String medicalRecords = '/home/profile/medical-records';
  static const String settings = '/home/profile/settings';
  static const String notificationsSettings = '/home/profile/settings/notifications';
  static const String helpSupport = '/home/profile/help';
  static const String privacyPolicy = '/home/profile/privacy';
  static const String termsOfService = '/home/profile/terms';
  static const String medicalId = '/home/profile/medical-id';
  static const String translation = '/home/profile/translation';
  static const String medications = '/home/medications';
  static const String addMedication = '/home/medications/add';
  static const String appointments = '/home/appointments';
  static const String addAppointment = '/home/appointments/add';
  static const String vitals = '/home/vitals';
  static const String addVital = '/home/vitals/add';
  static const String vitalsHistory = '/home/vitals/history';
  static const String aiChat = '/home/ai-chat';
  static const String sekerInfo = '/home/seker-info';
  static const String proPlan = '/home/pro-plan';
}
