-- ============================================================================
-- Migration 010: Storage RLS for medical-records + avatars buckets
-- ============================================================================
-- Purpose:
--   Enforce row-level security on Supabase Storage buckets so that:
--     1. medical-records files are only readable by their owning user
--     2. avatars are only readable by their owning user (write: same)
--     3. public access to PHI-bearing buckets is blocked at the storage layer
--
-- This is the server-side companion to the client-side fix in
-- medical_records_screen.dart (audit C-10). Even if a public URL were ever
-- generated by mistake, this RLS policy would block unauthenticated access.
--
-- Prerequisite: the `medical-records` bucket must exist. If it doesn't, this
-- migration creates it as a PRIVATE bucket (public = false).
-- ============================================================================

BEGIN;

-- ── 1. Create the medical-records bucket if it doesn't exist ──────────────
-- Private bucket (public = false) — all access goes through signed URLs or
-- RLS-evaluated storage policies.
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'medical-records',
  'medical-records',
  false,
  10485760,  -- 10 MB file size limit (matches client-side check, audit H-1)
  ARRAY[
    'image/jpeg',
    'image/png',
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
  ]
)
ON CONFLICT (id) DO UPDATE SET
  public = false,
  file_size_limit = 10485760,
  allowed_mime_types = ARRAY[
    'image/jpeg',
    'image/png',
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
  ];

-- ── 2. Storage RLS policies for medical-records ───────────────────────────
-- Files are stored under the path `{user_id}/{timestamp}_{filename}`. The
-- `storage.foldername(name, 1)` function extracts the first path segment,
-- which is the user_id. We compare it against auth.uid() to enforce
-- per-user isolation.

-- Allow users to read their own medical records
CREATE POLICY "Users can read own medical records"
  ON storage.objects FOR SELECT
  TO authenticated
  USING (
    bucket_id = 'medical-records'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

-- Allow users to upload to their own folder
CREATE POLICY "Users can upload own medical records"
  ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (
    bucket_id = 'medical-records'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

-- Allow users to update their own files (e.g. replace)
CREATE POLICY "Users can update own medical records"
  ON storage.objects FOR UPDATE
  TO authenticated
  USING (
    bucket_id = 'medical-records'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

-- Allow users to delete their own files
CREATE POLICY "Users can delete own medical records"
  ON storage.objects FOR DELETE
  TO authenticated
  USING (
    bucket_id = 'medical-records'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

-- ── 3. Storage RLS policies for avatars bucket ────────────────────────────
-- The avatars bucket already exists (migration 005). Add RLS policies so
-- files under `avatars/{user_id}/avatar.jpg` are only accessible by the
-- owning user. Profile pictures are PII — they shouldn't be publicly
-- fetchable without the user's consent.

-- First, make the avatars bucket private (was likely public before).
UPDATE storage.buckets SET public = false WHERE id = 'avatars';

CREATE POLICY "Users can read own avatar"
  ON storage.objects FOR SELECT
  TO authenticated
  USING (
    bucket_id = 'avatars'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

CREATE POLICY "Users can upload own avatar"
  ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (
    bucket_id = 'avatars'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

CREATE POLICY "Users can update own avatar"
  ON storage.objects FOR UPDATE
  TO authenticated
  USING (
    bucket_id = 'avatars'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

CREATE POLICY "Users can delete own avatar"
  ON storage.objects FOR DELETE
  TO authenticated
  USING (
    bucket_id = 'avatars'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

COMMIT;
